import { Container } from "@chakra-ui/react";
import Head from "next/head";

interface LayoutProps {
  title?: string;
  children?: React.ReactNode;
}

export const Layout: React.FC<LayoutProps> = ({ title = "Home", children }) => {
  return (
    <>
      <Head>
        <title>Ryan's log | {title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container my={10} maxW="container.lg">
          {children}
        </Container>
      </main>
    </>
  );
};
