import { GetStaticProps } from "next";
import Head from "next/head";
import { getAllPost } from "../utils/content-api";

export const getStaticProps: GetStaticProps = async (context) => {
  const posts = await getAllPost();

  console.log(posts);

  return {
    props: {
      posts,
    },
  };
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Ryan's Log</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>test</main>
    </>
  );
}
